Added test code for the linkedlist
rustc main.rs

thread 'main' panicked at 'already borrowed: BorrowMutError', /private/tmp/rust-20200509-70766-vc2112/rustc-1.43.1-src/src/libcore/cell.rs:878:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: core::result::Result<T,E>::expect
  10: core::cell::RefCell<T>::borrow_mut
  11: main::linkedlist::Cons<T>::append
  12: main::linkedlist::LinkedList<T>::append
  13: main::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start_internal
  18: std::rt::lang_start
  19: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.